//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string date { get; set; }
        public int ElectronicTypeId { get; set; }
        public string ElectronicModel { get; set; }
        public string ProblemDescription { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string OrderStatus { get; set; }
        public string MasterDescription { get; set; }
    
        public virtual ElectronicType ElectronicType { get; set; }
    }
}
